import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Navbar from 'components/Navbar'
import styled from 'styled-components'
import Link from "next/link";

const MainContainer = styled.div`
  display: flex;
  flex-direction: column;
  height: 100vh;
  width: 100vw;
  background: #a8dadc;
  
  justify-content: center;
  align-items: center;
  
  padding: 10rem;
`

const ContentText = styled.div`
  font-size: 1.75rem;
  text-align: center;
  
  padding: 1rem 0;
`;

const StartButton = styled.button`
  font-size: 2rem;
  background: #a8dadc;
  padding: 1rem;
  margin-top: 2rem;
  border: 4px solid #000;
  border-radius: 3rem;
  
  &:hover {
    background: #6aaaab;
  }
`

export default function About() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <MainContainer>
        <h1>Welcome</h1>
        <ContentText>This survey aims to understand and study the effectiveness of different forms of visualisations on consumers, and should take no more than 10 minutes to complete.</ContentText>
        <ContentText style={{fontSize:"1.5rem"}}>* Your answers are completely anonymous and will solely be used for research purposes.</ContentText>
        
        <Link href={`/survey-1`} style={{ textDecoration: "none" }}>
          <StartButton>Start Survey</StartButton>
        </Link>
        
      </MainContainer>
    </>
  )
}
