import Head from 'next/head'
import styled from 'styled-components'
import Link from "next/link";

import * as React from 'react';
import Radio from '@mui/material/Radio';
import RadioGroup from '@mui/material/RadioGroup';
import FormControlLabel from '@mui/material/FormControlLabel';
import FormControl from '@mui/material/FormControl';

import Image from 'next/image'
import Watch from '../../public/images/watch.jpg'

import Rating from '@mui/material/Rating';
import Box from '@mui/material/Box';
import StarIcon from '@mui/icons-material/Star';

import TextField from '@mui/material/TextField';

import Button from '@mui/material/Button';
import ArrowForwardIcon from '@mui/icons-material/ArrowForward';


const MainContainer = styled.div`
  display: flex;
  flex-direction: column;
  height: auto;
  width: auto;
  background: #F3F8FE;
  
  justify-content: center;
  align-items: center;
  
  padding: 10rem;
`
const SubContainer = styled.div`
  width: auto;
  max-width: 40rem;
  
  justify-content: left;
  align-items: left;
  
`;

const QuestionContainer = styled.div`
  width: 100%;
  height: 100%;
  background: #fff;
  padding: 1rem 3rem 2rem 3rem;
  border-radius: 1rem;
  margin: 2rem 0;
`;

const ContentText = styled.div`
  font-size: 1.375rem;
  font-weight: 400;
  text-align: left;
  
  padding: 1rem 0;
  margin-top: 1rem;
`;

const ImageIcon = styled.div`
    padding: 2rem;
    padding-left: 0;

`;

const labels = {
  0: '0',
  1: '1',
  2: '2',
  3: '3',
  4: '4',
  5: '5',
  6: '6',
  7: '7',
  8: '8',
  9: '9',
  10: '10',
};

function getLabelText(value) {
  return `${value} Star${value !== 1 ? 's' : ''}, ${labels[value]}`;
}



export default function Survey1() {
  
  const [value, setValue] = React.useState(0);
  const [hover, setHover] = React.useState(-1);

  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <MainContainer>
        <SubContainer>
          <h1 style={{fontSize:"2.5rem"}}>Product Scenario</h1>
          
          <ContentText>The story, all names, characters, and incidents portrayed in this example are fictitious. No identification with actual persons (living or deceased), places, buildings, and products is intended or should be inferred.</ContentText>
          
          <ContentText>Our company, BestWatches Inc., is testing a new product design for our watch lineup, tentatively known as The Constellations. We will show you the current design, then ask you for feedback.</ContentText>

          <ContentText>Please review the watch design.</ContentText>

            <ImageIcon>
              <Image
                src={Watch}
                alt="Two overlapping red and green squares"
                width={400}
                height={400}
              />
            </ImageIcon>
        
          <QuestionContainer>
            <ContentText>The design of The Constellation appeals to me.</ContentText>
            
            <FormControl>
              <RadioGroup
                aria-labelledby="demo-radio-buttons-group-label"
                name="age"
              >
                <FormControlLabel value="1" control={<Radio />} label="Strongly Disagree" />
                <FormControlLabel value="2" control={<Radio />} label="Disagree" />
                <FormControlLabel value="3" control={<Radio />} label="Neither Agree nor Disagree" />
                <FormControlLabel value="4" control={<Radio />} label="Agree" />
                <FormControlLabel value="5" control={<Radio />} label="Strongly Agree" />
              </RadioGroup>
            </FormControl>
          </QuestionContainer>
          
          <QuestionContainer>
            <ContentText>The Constellation stands out from the other brands available in the market.</ContentText>
            
            <FormControl>
              <RadioGroup
                aria-labelledby="demo-radio-buttons-group-label"
                name="age"
              >
                <FormControlLabel value="1" control={<Radio />} label="Strongly Disagree" />
                <FormControlLabel value="2" control={<Radio />} label="Disagree" />
                <FormControlLabel value="3" control={<Radio />} label="Neither Agree nor Disagree" />
                <FormControlLabel value="4" control={<Radio />} label="Agree" />
                <FormControlLabel value="5" control={<Radio />} label="Strongly Agree" />
              </RadioGroup>
            </FormControl>
          </QuestionContainer>

          <QuestionContainer>
            <ContentText>Based on the image, the quality of The Constellation is</ContentText>
            
            <FormControl>
              <RadioGroup
                aria-labelledby="demo-radio-buttons-group-label"
                name="age"
              >
                <FormControlLabel value="1" control={<Radio />} label="Very Poor" />
                <FormControlLabel value="2" control={<Radio />} label="Poor" />
                <FormControlLabel value="3" control={<Radio />} label="Acceptable" />
                <FormControlLabel value="4" control={<Radio />} label="Good" />
                <FormControlLabel value="5" control={<Radio />} label="Very Good" />
              </RadioGroup>
            </FormControl>
          </QuestionContainer>
          
          <QuestionContainer>
            <ContentText>I would buy The Constellation if it were available in the market.</ContentText>
            
            <FormControl>
              <RadioGroup
                aria-labelledby="demo-radio-buttons-group-label"
                name="age"
              >
                <FormControlLabel value="1" control={<Radio />} label="Very Unlikely" />
                <FormControlLabel value="2" control={<Radio />} label="Unlikely" />
                <FormControlLabel value="3" control={<Radio />} label="Neutral" />
                <FormControlLabel value="4" control={<Radio />} label="Likely" />
                <FormControlLabel value="5" control={<Radio />} label="Very Likely" />
              </RadioGroup>
            </FormControl>
          </QuestionContainer>
          
          <QuestionContainer>
            <ContentText>On a scale of 1 - 10, how useful are the provided images in helping you to answer the above 4 questions?</ContentText>

            <Box
              sx={{
                width:350,
                display: 'flex',
                alignItems: 'center',
              }}
            >
              <Rating
                name="hover-feedback"
                value={value}
                max={10}
                size="large"
                getLabelText={getLabelText}
                onChange={(event, newValue) => {
                  setValue(newValue);
                }}
                onChangeActive={(event, newHover) => {
                  setHover(newHover);
                }}
                emptyIcon={<StarIcon style={{ opacity: 0.55 }} fontSize="inherit" />}
              />
              {value !== null && (
                <Box sx={{ ml: 2 }}>{labels[hover !== -1 ? hover : value]}</Box>
              )}
            </Box>
          </QuestionContainer>
          
          <QuestionContainer>
            <ContentText>Comments (Optional)</ContentText>
            
            <TextField
              id="outlined-multiline-static"
              label="E.g. The watch is nice, but not my style."
              multiline
              rows={4}
              fullWidth
            />
          </QuestionContainer>
          
          
          
          <br />
          <br />
          
          <Link href={`/survey-3.html`} style={{ textDecoration: "none" }}>
            <Button variant="contained" endIcon={<ArrowForwardIcon />}>
              Next
            </Button>
          </Link>
        </SubContainer>
      </MainContainer>
    </>
  )
}
