import Head from 'next/head'
import styled from 'styled-components'
import Link from "next/link";

import * as React from 'react';
import Radio from '@mui/material/Radio';
import RadioGroup from '@mui/material/RadioGroup';
import FormControlLabel from '@mui/material/FormControlLabel';
import FormControl from '@mui/material/FormControl';

import Button from '@mui/material/Button';
import ArrowForwardIcon from '@mui/icons-material/ArrowForward';


const MainContainer = styled.div`
  display: flex;
  flex-direction: column;
  height: 100vh;
  width: 100vw;
  background: #fffff;
  
  justify-content: center;
  align-items: center;
  
  padding: 10rem;
`

const ContentText = styled.div`
  font-size: 1.75rem;
  font-weight: 500;
  text-align: center;
  
  padding: 1rem 0;
  margin-top: 2rem;
`;


export default function Survey1() {
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <MainContainer>
        <h1 style={{fontSize:"2.5rem"}}>General Questions</h1>
        <ContentText>1. How old are you?</ContentText>

        <FormControl>
          <RadioGroup
            aria-labelledby="demo-radio-buttons-group-label"
            name="age"
          >
            <FormControlLabel value="<18" control={<Radio />} label="Under 18" />
            <FormControlLabel value="18-24" control={<Radio />} label="18 - 24" />
            <FormControlLabel value="25-34" control={<Radio />} label="25 - 34" />
            <FormControlLabel value="35-44" control={<Radio />} label="25 - 44" />
            <FormControlLabel value="45-54" control={<Radio />} label="45 - 54" />
            <FormControlLabel value="55-64" control={<Radio />} label="55 - 64" />
            <FormControlLabel value=">65" control={<Radio />} label="65 and over" />
          </RadioGroup>
        </FormControl>
        
        <ContentText>2. What is your gender?</ContentText>
        
        <FormControl>
          <RadioGroup
            aria-labelledby="demo-radio-buttons-group-label"
            name="gender"
          >
            <FormControlLabel value="M" control={<Radio />} label="Male" />
            <FormControlLabel value="F" control={<Radio />} label="Female" />
            <FormControlLabel value="O" control={<Radio />} label="Other" />
          </RadioGroup>
        </FormControl>
        
        <br />
        <br />
        
        <Link href={`/survey-2`} style={{ textDecoration: "none" }}>
          <Button variant="contained" endIcon={<ArrowForwardIcon />}>
            Next
          </Button>
        </Link>
        
      </MainContainer>
    </>
  )
}
